version: "3.9"
services:
  postgres:
    image: av-docker.artifactory.av.ge.com/av-cp-techpubs/pgcrypto-postgres:13.1
    user: postgres
    container_name: dc-postgres
    volumes:
      - ${HOME}/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - techpubs-network

  techpubs-config-service:
    image: av-docker.artifactory.av.ge.com/av-cp-techpubs/local-config-server:1.4
    container_name: techpubs-config-server
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD
    expose:
      - 8888
    ports:
      - 8888:8888
    networks:
      - techpubs-network
networks:
  techpubs-network:
    driver: bridge